# Warning: Large block split
<div id="LC82" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">    <span class=pl-s1>filename_pattern_help</span> <span class=pl-c1>=</span> <span class=pl-s>&quot;&quot;&quot;</span></div>
<div id="LC83" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div "><span class=pl-s>    Filename pattern to use when creating output files.</span></div>
<div id="LC84" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div "><span class=pl-s>    The sequential file number and the format are available.</span></div>
<div id="LC85" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div "><span class=pl-s>    Default: schematic-%%(counter)d.%%(format)s</span></div>
<div id="LC86" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div "><span class=pl-s>    Use stdout to write to stdout</span></div>
<div id="LC87" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div "><span class=pl-s>        &quot;&quot;&quot;</span></div>
<div id="LC88" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">    <span class=pl-s1>parser</span> <span class=pl-c1>=</span> <span class=pl-s1>argparse</span>.<span class=pl-c1>ArgumentParser</span>(<span class=pl-s1>description</span><span class=pl-c1>=</span><span class=pl-s1>desc</span>)</div>
<div id="LC89" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">    <span class=pl-s1>parser</span>.<span class=pl-c1>add_argument</span>(<span class=pl-s>&quot;--format&quot;</span>, <span class=pl-s1>action</span><span class=pl-c1>=</span><span class=pl-s>&quot;store&quot;</span>, <span class=pl-s1>default</span><span class=pl-c1>=</span><span class=pl-s>&quot;SVG&quot;</span>,</div>
<div id="LC90" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">                        <span class=pl-s1>help</span><span class=pl-c1>=</span><span class=pl-s>&quot;Output schematic file format (SVG)&quot;</span>)</div>
<div id="LC91" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">    <span class=pl-s1>parser</span>.<span class=pl-c1>add_argument</span>(<span class=pl-s>&quot;--in_spec&quot;</span>, <span class=pl-s1>action</span><span class=pl-c1>=</span><span class=pl-s>&quot;store&quot;</span>, <span class=pl-s1>required</span><span class=pl-c1>=</span><span class=pl-c1>True</span>,</div>
<div id="LC92" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">                        <span class=pl-s1>help</span><span class=pl-c1>=</span><span class=pl-s>&quot;Input file path. Use stdin to read standard in&quot;</span>)</div>