# Warning: Large block split
<div id="LC93" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">    <span class=pl-s1>parser</span>.<span class=pl-c1>add_argument</span>(<span class=pl-s>&quot;--out_spec&quot;</span>, <span class=pl-s1>action</span><span class=pl-c1>=</span><span class=pl-s>&quot;store&quot;</span>,</div>
<div id="LC94" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">                        <span class=pl-s1>default</span><span class=pl-c1>=</span><span class=pl-s>&quot;./schematic-%(counter)d.%(format)s&quot;</span>,</div>
<div id="LC95" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">                        <span class=pl-s1>help</span><span class=pl-c1>=</span><span class=pl-s1>filename_pattern_help</span>)</div>
<div id="LC96" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">    <span class=pl-s1>args</span> <span class=pl-c1>=</span> <span class=pl-s1>parser</span>.<span class=pl-c1>parse_args</span>()</div>
<div id="LC97" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">
</div>
<div id="LC98" class="react-code-text react-code-line-contents-no-virtualization react-file-line html-div ">    <span class=pl-en>convertFile</span>(<span class=pl-s1>args</span>)</div></div></div></div></div><div id="copilot-button-container"></div></div><div id="highlighted-line-menu-container"></div></div></div><button hidden="" data-testid="hotkey-button" data-hotkey-scope="read-only-cursor-text-area"></button><button hidden=""></button></section></div></div></div> <!-- --> <!-- --> </div></div></div><div class="Box-sc-g0xbh4-0"></div></div></div></div></div><div id="find-result-marks-container" class="Box-sc-g0xbh4-0 cCoXib"></div><button hidden="" data-testid="" data-hotkey-scope="read-only-cursor-text-area"></button><button hidden=""></button></div> <!-- --> <!-- --> <script type="application/json" id="__PRIMER_DATA_:R0:__">{"resolvedServerColorMode":"night"}</script></div>
</react-app>
</turbo-frame>
