name: Security Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run Bandit
      run: |
        bandit -r . -c .bandit -f json -o bandit-report.json
        bandit -r . -c .bandit -f txt -o bandit-report.txt
      continue-on-error: true
    
    - name: Run Safety Check
      run: |
        safety check --json > safety-report.json
        safety check --full-report > safety-report.txt
      continue-on-error: true
    
    - name: Upload Security Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: |
          bandit-report.*
          safety-report.*
